shared_parameters:
  grader_root: "/autograder/course-materials/labs/lab01/grader/submit"
  submission_root: "/autograder/submission/lab01/src"
  command_timeout: 10
  assignment_id: lab01

execution_plan:
  - gradescope.sub_info
  - beacon.extensions
  - jh61b.check_files:
      pieces:
        ArithmeticTest:
          student_files:
            - Arithmetic.java
          assessment_files:
            - ArithmeticTest.java
  - jh61b.compilation
  - jh61b.dep_check
  - jh61b.assessment:
      piece_configs:
        ArithmeticTest:
          require_full_score: true
          aggregated_number: 1
  - jh61b.magic_word:
      # two words, the first starts with the character that the second ends with
      # example: "lol cs61bl"
      magic_word_path: "../magic_word.txt"
      magic_word_regex: "(?i)^(\\w)\\w* \\w*\\1$"
  - jh61b.final_score:
      scoring:
        ArithmeticTest: 1
      penalties:
        jh61b.magic_word: 1
      max_points: 128

teardown_plan:
  - jh61b.motd
  - gradescope.lateness
  - gradescope.results
